---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nyan-ingress
  labels:
    app: nyan-cat
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/rewrite-target: /$1/
spec:
  rules:
    - host: k8spi.lan
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nyan-service
                port:
                  number: 80
